version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    # restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - CONNECTION=mongodb://mongo1:27017/kiddiecove
    container_name: backend
    volumes:
      - .:/usr/src
    networks:
      - mongors-network

  mongo1:
    container_name: mongo1
    image: mongo:latest
    volumes:
      - ./docker-compose-stuff/db:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    ports:
      - 27017:27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']

  mongo2:
    container_name: mongo2
    image: mongo:latest
    networks:
      - mongors-network
    ports:
      - 27018:27017
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']

  mongo3:
    container_name: mongo3
    image: mongo:latest
    networks:
      - mongors-network
    ports:
      - 27019:27017
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']

networks:
  mongors-network:
    driver: bridge
